sudo: required
services:
- docker
env:
  global:
  - IMAGE_NAME=otokarev/lightningnetwork-lnd
branches:
  only:
  - master
  - bare
  - /^v.*$/
before_script:
- if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
- sed -i 's/^ENV\s+VERSION.*$/ENV VERSION='$TRAVIS_TAG'/' Dockerfile;
- docker pull "$IMAGE_NAME" || true
script:
- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" -f Dockerfile .
after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:latest"
